name: Deploy CI

on:
  push:
    branches:
      - dev
      - gh-pages
      - feature/gh-pages
  pull_request:
    branches:
      - dev
jobs:
  develop-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn

      - name: Build Dapp
        run: yarn build:xdai

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: gh-pages 
          FOLDER: build 
          CLEAN: true 
