name: Deploy Github Pages 
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Dapp
        run: npm run build:xdai

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          ssh-key: ${{ secrets.GITHUB_PAGES }}
          branch: gh-pages 
          folder: build 
          clean: true 
