name: Develop CI/CD

on:
  push:
    branches:
      - github_action
      - main
  pull_request:
    branches:
      - main
jobs:
  develop-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Remove dependencies
        run: rm -rf package-lock.json node_modules
      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage --passWithNoTests

      - name: Build
        run: npm run build
  develop-deploy:
    runs-on: ubuntu-latest
    needs: [develop-ci]
    steps:
      - uses: actions/checkout@v2
      # ( Build to ./dist or other directory... )
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.LEE_MESA_INTERFACE }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1