name: Develop CI/CD

on:
  push:
    branches:
      - github_action
jobs:
  develop-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
  # develop-deploy:
  #   runs-on: ubuntu-latest
  #   needs: [develop-ci]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{secrets.DEV_NODE_IP}}
  #         username: ubuntu
  #         key: ${{ secrets.SSH_KEY }}
  #         port: 22
  #         script: |
  #           /bin/sh ./mesa-interface/develop_deploy.sh